gg:
  jte:
    development-mode: false
    usePrecompiledTemplates: true

ibkr:
  data-url: ${IBKR_DATA_URL}

alpaca:
  data-url: ${ALPACA_DATA_URL}
  api-key: ${ALPACA_API_KEY}
  secret-key: ${ALPACA_API_SECRET_KEY}

server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: srcprofit
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SRCPROFIT_DB_URL}
    username: ${SRCPROFIT_DB_USER}
    password: ${SRCPROFIT_DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        fetch_size: 50 
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
    show-sql: false
    open-in-view: false

management:
  endpoint:
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS
    health:
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: ping
          show-details: always
        readiness:
          include: '*'
          show-details: always
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'prometheus', 'shutdown']
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'

